// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/12/2026, 10:23:20 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/marquis/campus-link/admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/campus-link/admin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/campus-link/admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/campus-link/admin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/campus-link/admin/plugins/**/*.{js,ts,mjs}","/Users/marquis/campus-link/admin/composables/**/*.{js,ts,mjs}","/Users/marquis/campus-link/admin/composables/**/**/*.{js,ts,mjs}","/Users/marquis/campus-link/admin/composables/core/**/*.{js,ts,mjs}","/Users/marquis/campus-link/admin/composables/modules/**/**/*.{js,ts,mjs}","/Users/marquis/campus-link/admin/utils/**/*.{js,ts,mjs}","/Users/marquis/campus-link/admin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/campus-link/admin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/campus-link/admin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/campus-link/admin/app.config.{js,ts,mjs}","/Users/marquis/campus-link/admin/app/spa-loading-template.html"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;