// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/5/2026, 10:00:47 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/mac/Documents/campus-link/admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/campus-link/admin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/campus-link/admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/campus-link/admin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/campus-link/admin/plugins/**/*.{js,ts,mjs}","/Users/mac/Documents/campus-link/admin/composables/**/*.{js,ts,mjs}","/Users/mac/Documents/campus-link/admin/composables/**/**/*.{js,ts,mjs}","/Users/mac/Documents/campus-link/admin/composables/modules/**/**/*.{js,ts,mjs}","/Users/mac/Documents/campus-link/admin/utils/**/*.{js,ts,mjs}","/Users/mac/Documents/campus-link/admin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/campus-link/admin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/campus-link/admin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/campus-link/admin/app.config.{js,ts,mjs}","/Users/mac/Documents/campus-link/admin/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;